export const ActionTypes = {
    GET_ORDERS: "GET_ORDERS",
    CREATE_ORDER: "CREATE_ORDER",
    DELETE_ORDER: "DELETE_ORDER",
    UPDATE_ORDER: "UPDATE_ORDER",
    REGISTER_USER: "REGISTER_USER",
    LOGIN_USER: "LOGIN_USER",
    LOGOUT_USER: "LOGOUT_USER",
    SEARCH_ORDER:"SEARCH_ORDER",
    SAVE_VALUE:"SAVE_VALUE"
}